controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_joint_controller:
      type: forward_command_controller/ForwardCommandController

arm_joint_controller:
  ros__parameters:
    joints: ["arm_joint1","arm_joint2"]
    interface_name: "position"

